FROM mcr.microsoft.com/dotnet/sdk:8.0 as stage1
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=stage1 /app/out .
ENTRYPOINT [ "dotnet", "AspNetCoreCustomersWebApi.dll" ]